# Generated by Django 5.0.4 on 2025-04-15 19:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XMLFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Name of the XML file', max_length=255)),
                ('content', models.TextField(help_text='XML file content stored as text')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'XML File',
                'verbose_name_plural': 'XML Files',
                'db_table': 'xml_file',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
