# Generated by Django 5.0.4 on 2025-04-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlfile',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original name of the uploaded XML file', max_length=255, null=True),
        ),
    ]
